-- BEOS Database Schema for Supabase (PostgreSQL)

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Users (Managed by Supabase Auth, but we extend public.users or just use auth.users linkages)
-- Note: In Supabase, generally we reference auth.users. 
-- However, for this migration, we'll keep a 'public.profiles' or similar to map to our existing logic, 
-- or we can map existing 'users' table to public.users and link to auth.users.
-- For simplicity and strict migration effectively:
-- We will create a public.users table that links to auth.users if possible, or just standalone for now.
-- STRATEGY: Create tables that match the application logic, assuming 'user_id' will eventually link to auth.users.id

-- 1. Users Table (Application specific metadata)
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Linked to auth.users.id
    user_id UUID REFERENCES auth.users(id), 
    email TEXT UNIQUE NOT NULL,
    role TEXT DEFAULT 'user' CHECK(role IN ('user', 'admin', 'hospital', 'blood_bank', 'donor')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Donors Table
CREATE TABLE public.donors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id),
    name TEXT NOT NULL,
    blood_type TEXT NOT NULL CHECK(blood_type IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')),
    phone TEXT NOT NULL,
    email TEXT,
    city TEXT NOT NULL,
    address TEXT,
    available BOOLEAN DEFAULT TRUE,
    last_donation DATE,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Hospitals Table
CREATE TABLE public.hospitals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id),
    name TEXT NOT NULL,
    address TEXT NOT NULL,
    city TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    emergency_contact TEXT,
    verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Blood Banks Table
CREATE TABLE public.blood_banks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id),
    name TEXT NOT NULL,
    address TEXT NOT NULL,
    city TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    operating_hours TEXT,
    verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Blood Inventory (Summary)
CREATE TABLE public.blood_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blood_bank_id BIGINT NOT NULL REFERENCES public.blood_banks(id),
    blood_type TEXT NOT NULL CHECK(blood_type IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')),
    units INTEGER DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(blood_bank_id, blood_type)
);

-- 6. Blood Batches (Detailed Inventory)
CREATE TABLE public.blood_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blood_bank_id BIGINT NOT NULL REFERENCES public.blood_banks(id),
    blood_type TEXT NOT NULL CHECK(blood_type IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')),
    units INTEGER NOT NULL,
    expiry_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Blood Requests
CREATE TABLE public.blood_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id BIGINT REFERENCES public.hospitals(id),
    donor_id BIGINT REFERENCES public.donors(id), -- If fulfilled by specific donor
    patient_name TEXT,
    age INTEGER,
    gender TEXT,
    hemoglobin DOUBLE PRECISION,
    platelets INTEGER,
    blood_type TEXT NOT NULL CHECK(blood_type IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')),
    units INTEGER NOT NULL DEFAULT 1,
    component_type TEXT DEFAULT 'Whole Blood',
    urgency TEXT DEFAULT 'normal' CHECK(urgency IN ('normal', 'urgent', 'critical')),
    is_critical BOOLEAN DEFAULT FALSE,
    diagnosis TEXT,
    past_reaction TEXT,
    allergies TEXT,
    doctor_name TEXT,
    status TEXT DEFAULT 'pending' CHECK(status IN ('pending', 'fulfilled', 'cancelled')),
    contact_phone TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    fulfilled_at TIMESTAMPTZ
);

-- 8. Donations
CREATE TABLE public.donations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_id BIGINT NOT NULL REFERENCES public.donors(id),
    blood_bank_id BIGINT REFERENCES public.blood_banks(id),
    request_id BIGINT REFERENCES public.blood_requests(id),
    blood_type TEXT NOT NULL,
    units INTEGER DEFAULT 1,
    donation_date TIMESTAMPTZ DEFAULT NOW(),
    notes TEXT
);

-- ROW LEVEL SECURITY (RLS) POLICIES
-- NOTE: In a real production environment with Supabase Auth, we would check auth.uid()
-- For now, we enable RLS but allow public access or basic logic to prepare for Auth integration.

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hospitals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blood_banks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blood_requests ENABLE ROW LEVEL SECURITY;

-- Policy: Everyone can read basic hospital/blood bank info
CREATE POLICY "Public read access to hospitals" ON public.hospitals FOR SELECT USING (true);
CREATE POLICY "Public read access to blood_banks" ON public.blood_banks FOR SELECT USING (true);

-- Policy: Donors can only update their own profile (Placeholder logic)
-- CREATE POLICY "Donors update own profile" ON public.donors FOR UPDATE USING (auth.uid() = user_id);

-- Indexes
CREATE INDEX idx_donors_blood_type ON public.donors(blood_type);
CREATE INDEX idx_donors_city ON public.donors(city);
CREATE INDEX idx_blood_requests_status ON public.blood_requests(status);
CREATE INDEX idx_blood_requests_urgency ON public.blood_requests(urgency);
CREATE INDEX idx_blood_batches_expiry ON public.blood_batches(expiry_date);
